import { NextApiRequest, NextApiResponse } from 'next'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

/**
 * Send test error email for missing tag
 */
async function sendTestTagNotFoundEmail(tagName: string) {
  try {
    const recipients = [
      'jonathan@jpierce.dev'  // Just sending to you for testing
    ]

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #dc2626;">Virtuous Tag Not Found - TEST EMAIL</h2>
        <p>This is a test email to demonstrate the error notification system for missing Virtuous tags.</p>
        
        <div style="background-color: #fef2f2; border: 1px solid #fecaca; padding: 16px; border-radius: 8px; margin: 16px 0;">
          <h3 style="color: #dc2626; margin-top: 0;">Missing Tag Details:</h3>
          <p><strong>Tag Name:</strong> ${tagName}</p>
          <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Status:</strong> TEST - This tag was intentionally tested to trigger this email</p>
        </div>

        <h3>What This Email Means:</h3>
        <p>When a user subscribes with a marketing source parameter (like <code>?src=${tagName}</code>), the system tries to tag them in Virtuous. If the tag doesn't exist, this email is automatically sent to notify the team.</p>

        <h3>Action Required (In Real Scenarios):</h3>
        <ul>
          <li>Create the tag "${tagName}" in Virtuous if it should exist</li>
          <li>Verify the marketing campaign is using the correct tag name</li>
          <li>Check for typos in the campaign URLs</li>
        </ul>

        <h3>System Details:</h3>
        <p><strong>Recipients:</strong> mtapia@gracewoodlands.com, jonathan@jpierce.dev, jpierce@gracewoodlands.com</p>
        <p><strong>Trigger:</strong> User subscription with unknown marketing source</p>
        <p><strong>Frequency:</strong> One email per unique missing tag per day</p>
        
        <p style="color: #6b7280; font-size: 14px; margin-top: 24px;">
          This email was automatically generated by the Forge Journal marketing attribution system.
        </p>
      </div>
    `

    const result = await resend.emails.send({
      from: 'The Forge Journal <notifications@theforgejournal.com>',
      to: recipients,
      subject: `TEST: Missing Virtuous Tag - "${tagName}"`,
      html: emailHtml,
    })

    console.log(`Sent test tag not found email for: ${tagName}`, result)
    return result
  } catch (error) {
    console.error('Failed to send test tag not found email:', error)
    throw error
  }
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    const { tagName = 'test-missing-tag' } = req.body

    console.log(`Sending test error email for missing tag: ${tagName}`)

    const result = await sendTestTagNotFoundEmail(tagName)

    return res.status(200).json({
      success: true,
      message: `Test error email sent successfully for tag: ${tagName}`,
      emailResult: result
    })

  } catch (error) {
    console.error('Test error email failed:', error)
    return res.status(500).json({
      error: 'Failed to send test email',
      details: error instanceof Error ? error.message : 'Unknown error'
    })
  }
}
